config/routes.rb
Rails.application.routes.draw do

  devise_for :companies, controllers: {
    registrations:  "companies/registrations",
    sessions:       "companies/sessions",
    passwords:      "companies/passwords"
  }

  root to: "dashboard#index"

  match '/account/login', to: 'account#login', via: 'get'
  match '/account/registration', registrationto: 'account#', via: 'get'

  resources :projects do
    resources :comments, except: [:index, :show, :delete]
  end
  match 'order_projects', to: 'projects#order_index', via: 'get'
  match 'receive_projects', to: 'projects#receive_index', via: 'get'

  resources :commitments, except: [:show]

  resources :reviews, only: [:new, :create]

  resources :companies
end

app/views/shared/_core_js.html.erb
  <!-- Core JS files -->
  <script type="text/javascript" src="/assets/js/plugins/loaders/pace.min.js"></script>
  <script type="text/javascript" src="/assets/js/core/libraries/jquery.min.js"></script>
  <script type="text/javascript" src="/assets/js/core/libraries/bootstrap.min.js"></script>
  <script type="text/javascript" src="/assets/js/plugins/loaders/blockui.min.js"></script>
  <!-- /core JS files -->

app/views/shared/_footer.html.erb
  <!-- Footer -->
  <div class="footer text-muted">
    &copy; 2015. <a href="#">imaTat</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Kohki OBATA</a>
  </div>
  <!-- /footer -->

app/views/shared/_global_style.html.erb
  <!-- Global stylesheets -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
  <link href="/assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/core.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/components.min.css" rel="stylesheet" type="text/css">
  <link href="/assets/css/colors.min.css" rel="stylesheet" type="text/css">
  <!-- /global stylesheets -->

app/views/shared/_header.html.erb
  <!-- Main navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.html">imaTat</a>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
      <ul class="nav navbar-nav">
        <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
      </ul>

      <p class="navbar-text"><span class="label bg-success-400">Online</span></p>

      <% if company_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-user">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <img src="/assets/images/placeholder.jpg" alt="">
            <span><%= current_company.name%></span>
            <i class="caret"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to 'アカウント編集', edit_company_registration_path %></li>
            <li><%= link_to "ログアウト", destroy_company_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-user">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <img src="/assets/images/placeholder.jpg" alt="">
            <span>ログイン or 会員登録</span>
            <i class="caret"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to 'ログイン', new_company_session_path %></li>
            <li><%= link_to '会員登録', new_company_registration_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
  <!-- /main navbar -->

  <!-- Horizontal form modal -->
  <div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h5 class="modal-title">アカウント編集</h5>
        </div>

        <form action="#" class="form-horizontal">
          <div class="modal-body">
            <div class="panel-body">
              <div class="form-group">
                <label>登録Eメール：</label>
                <input type="text" class="form-control" value="imatat@tatami.jp">
              </div>

              <div class="form-group">
                <label>企業名：</label>
                <input type="text" class="form-control" value="(株)イマタット畳店">
              </div>

              <div class="form-group">
                <label>郵便番号：</label>
                <input type="text" class="form-control" value="123-1234">
              </div>

              <div class="form-group">
                <label>住所：</label>
                <input type="text" class="form-control" value="東京都日野市南平1-1">
              </div>

              <div class="form-group">
                <label class="display-block">都道府県:</label>
                <select data-placeholder="東京" class="select-fixed" value="東京都">
                  <option></option>
                    <option value="AK">北海道</option>
                    <option value="HI">青森</option>
                    <option value="CA">秋田</option>
                    <option value="NV">岩手</option>
                    <option value="WA">東京</option>
                    <option value="AZ">千葉</option>
                  </optgroup>
                </select>
              </div>

              <div class="form-group">
                <label>日産(枚)：</label>
                <input type="text" class="form-control" value="6">
              </div>

              <div class="form-group">
                <label>従業員数(人)：</label>
                <input type="text" class="form-control" value="2">
              </div>

              <div class="form-group">
                <label>電話番号：</label>
                <input type="text" class="form-control" value="012-345-6789">
              </div>

              <div class="form-group">
                <label>パスワード：</label>
                <input type="password" class="form-control" value="">
              </div>

              <div class="form-group">
                <label>パスワード再入力：</label>
                <input type="password" class="form-control" value="">
              </div>

              <div class="form-group">
                <label>プロフィール画像：</label>
                <input type="file" class="file-styled">
              </div>

              <div class="form-group">
                <label>企業紹介:</label>
                <textarea rows="5" cols="5" class="form-control" value="企業紹介"></textarea>
              </div>

              <div class="form-group">
                <label class="display-block">忙しさ:</label>
                <select data-placeholder="忙しい" class="select-fixed" value="忙しい">
                  <option></option>
                    <option value="highest">とても忙しい</option>
                    <option value="high">忙しい</option>
                    <option value="normal">普通</option>
                    <option value="low">あまり忙しくない</option>
                    <option value="lowest">忙しくない</option>
                  </optgroup>
                </select>
              </div>

              <div class="checkbox checkbox-switchery">
                <label>
                  <input type="checkbox" class="switchery">
                  非公開設定
                  <span class="help-block">onにすると企業一覧に表示されなくなります</span>
                </label>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit form</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /horizontal form modal -->

app/views/shared/_header_aft.html.erb
  <!-- Main navbar -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">imaTat</a>
    </div>

    <div class="navbar-collapse collapse" id="navbar-mobile">
      <ul class="nav navbar-nav">
        <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
      </ul>

      <p class="navbar-text"><span class="label bg-success-400">Online</span></p>

      <% if company_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-user">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <img src="/assets/images/placeholder.jpg" alt="">
            <span><%= current_company.name%></span>
            <i class="caret"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="#" data-toggle="modal" data-target="#modal_form_horizontal">アカウント編集</a></li>
            <li><%= link_to "ログアウト", destroy_company_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown dropdown-user">
          <a class="dropdown-toggle" data-toggle="dropdown">
            <img src="/assets/images/placeholder.jpg" alt="">
            <span>ログイン or 会員登録</span>
            <i class="caret"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to 'ログイン', new_company_session_path %></li>
            <li><%= link_to '会員登録', new_company_registration_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>

    </div>
  </div>
  <!-- /main navbar -->

  <!-- Horizontal form modal -->
  <div id="modal_form_horizontal" class="modal fade">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h5 class="modal-title">アカウント編集</h5>
        </div>

        <form action="#" class="form-horizontal">
          <div class="modal-body">
            <div class="panel-body">
              <div class="form-group">
                <label>登録Eメール：</label>
                <input type="text" class="form-control" value="imatat@tatami.jp">
              </div>

              <div class="form-group">
                <label>企業名：</label>
                <input type="text" class="form-control" value="(株)イマタット畳店">
              </div>

              <div class="form-group">
                <label>郵便番号：</label>
                <input type="text" class="form-control" value="123-1234">
              </div>

              <div class="form-group">
                <label>住所：</label>
                <input type="text" class="form-control" value="東京都日野市南平1-1">
              </div>

              <div class="form-group">
                <label class="display-block">都道府県:</label>
                <select data-placeholder="東京" class="select-fixed" value="東京都">
                  <option></option>
                    <option value="AK">北海道</option>
                    <option value="HI">青森</option>
                    <option value="CA">秋田</option>
                    <option value="NV">岩手</option>
                    <option value="WA">東京</option>
                    <option value="AZ">千葉</option>
                  </optgroup>
                </select>
              </div>

              <div class="form-group">
                <label>日産(枚)：</label>
                <input type="text" class="form-control" value="6">
              </div>

              <div class="form-group">
                <label>従業員数(人)：</label>
                <input type="text" class="form-control" value="2">
              </div>

              <div class="form-group">
                <label>電話番号：</label>
                <input type="text" class="form-control" value="012-345-6789">
              </div>

              <div class="form-group">
                <label>パスワード：</label>
                <input type="password" class="form-control" value="">
              </div>

              <div class="form-group">
                <label>パスワード再入力：</label>
                <input type="password" class="form-control" value="">
              </div>

              <div class="form-group">
                <label>プロフィール画像：</label>
                <input type="file" class="file-styled">
              </div>

              <div class="form-group">
                <label>企業紹介:</label>
                <textarea rows="5" cols="5" class="form-control" value="企業紹介"></textarea>
              </div>

              <div class="form-group">
                <label class="display-block">忙しさ:</label>
                <select data-placeholder="忙しい" class="select-fixed" value="忙しい">
                  <option></option>
                    <option value="highest">とても忙しい</option>
                    <option value="high">忙しい</option>
                    <option value="normal">普通</option>
                    <option value="low">あまり忙しくない</option>
                    <option value="lowest">忙しくない</option>
                  </optgroup>
                </select>
              </div>

              <div class="checkbox checkbox-switchery">
                <label>
                  <input type="checkbox" class="switchery">
                  非公開設定
                  <span class="help-block">onにすると企業一覧に表示されなくなります</span>
                </label>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit form</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /horizontal form modal -->

app/views/shared/_header_bfr.html.erb
  <!-- Header bfr -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.html">imaTat</a>
    </div>
  </div>
  <!-- /header bfr -->

app/views/shared/_modal_account.html.erb
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">アカウント編集</h5>
      </div>

      <%= form_for(@company, remote: true) do |f| %>
      <form action="#" class="form-horizontal">
        <div class="modal-body">
          <div class="panel-body">
            <div class="form-group">
              <label>登録Eメール：</label>
              <%= f.text_field :email %>
              <input type="text" class="form-control" value="imatat@tatami.jp">
            </div>

            <div class="form-group">
              <label>企業名：</label>
              <input type="text" class="form-control" value="(株)イマタット畳店">
            </div>

            <div class="form-group">
              <label>郵便番号：</label>
              <input type="text" class="form-control" value="123-1234">
            </div>

            <div class="form-group">
              <label>住所：</label>
              <input type="text" class="form-control" value="東京都日野市南平1-1">
            </div>

            <div class="form-group">
              <label class="display-block">都道府県:</label>
              <select data-placeholder="東京" class="select-fixed" value="東京都">
                <option></option>
                  <option value="AK">北海道</option>
                  <option value="HI">青森</option>
                  <option value="CA">秋田</option>
                  <option value="NV">岩手</option>
                  <option value="WA">東京</option>
                  <option value="AZ">千葉</option>
                </optgroup>
              </select>
            </div>

            <div class="form-group">
              <label>日産(枚)：</label>
              <input type="text" class="form-control" value="6">
            </div>

            <div class="form-group">
              <label>従業員数(人)：</label>
              <input type="text" class="form-control" value="2">
            </div>

            <div class="form-group">
              <label>電話番号：</label>
              <input type="text" class="form-control" value="012-345-6789">
            </div>

            <div class="form-group">
              <label>パスワード：</label>
              <input type="password" class="form-control" value="">
            </div>

            <div class="form-group">
              <label>パスワード再入力：</label>
              <input type="password" class="form-control" value="">
            </div>

            <div class="form-group">
              <label>プロフィール画像：</label>
              <input type="file" class="file-styled">
            </div>

            <div class="form-group">
              <label>企業紹介:</label>
              <textarea rows="5" cols="5" class="form-control" value="企業紹介"></textarea>
            </div>

            <div class="form-group">
              <label class="display-block">忙しさ:</label>
              <select data-placeholder="忙しい" class="select-fixed" value="忙しい">
                <option></option>
                  <option value="highest">とても忙しい</option>
                  <option value="high">忙しい</option>
                  <option value="normal">普通</option>
                  <option value="low">あまり忙しくない</option>
                  <option value="lowest">忙しくない</option>
                </optgroup>
              </select>
            </div>

            <div class="checkbox checkbox-switchery">
              <label>
                <input type="checkbox" class="switchery">
                非公開設定
                <span class="help-block">onにすると企業一覧に表示されなくなります</span>
              </label>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit form</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /horizontal form modal -->

app/views/shared/_modal_review.html.erb
<!-- Horizontal form modal -->
<div id="modal_form_horizontal" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h5 class="modal-title">レビュー</h5>
      </div>

      <form class="form-horizontal" action="#">
        <div class="modal-body">
          <div class="row">
            <div class="col-md-8">
              <fieldset>
                <div class="form-group">
                  <label class="col-lg-3 control-label">依頼元企業:</label>
                  <div class="col-lg-9">
                    <input type="text" class="form-control" value="(有)八巻畳工業" disabled="true">
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">依頼先企業:</label>
                  <div class="col-lg-9">
                    <input type="text" class="form-control" value="依頼先企業1" disabled="true">
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">案件名:</label>
                  <div class="col-lg-9">
                    <input type="text" class="form-control" value="団地の畳表替え" disabled="true">
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">タイトル:</label>
                  <div class="col-lg-9">
                    <input type="text" class="form-control" placeholder="タイトル">
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-lg-3 control-label">本文:</label>
                  <div class="col-lg-9">
                    <textarea rows="10" cols="5" class="form-control" placeholder="詳細"></textarea>
                  </div>
                </div>
              </fieldset>
            </div>

            <div class="col-md-4">
              <fieldset>
                <div class="form-group">
                  <label>対応の丁寧さ: </label><br>
                  <input type="text" value="" class="touchspin-empty">
                </div>

                <div class="form-group">
                  <label>契約までの速さ: </label><br>
                  <input type="text" value="" class="touchspin-empty">
                </div>

                <div class="form-group">
                  <label>仕上がりの丁寧さ: </label><br>
                  <input type="text" value="" class="touchspin-empty">
                </div>

                <div class="form-group">
                  <label>納品までの早さ: </label><br>
                  <input type="text" value="" class="touchspin-empty">
                </div>

                <div class="form-group">
                  <label>価格: </label><br>
                  <input type="text" value="" class="touchspin-empty">
                </div>
              </fieldset>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-link" data-dismiss="modal">閉じる</button>
            <button type="submit" class="btn btn-primary">保存する</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /horizontal form modal -->

app/views/shared/_sidebar.html.erb
      <!-- Main sidebar -->
      <div class="sidebar sidebar-main sidebar-fixed">
        <div class="sidebar-content">

          <!-- User menu -->
          <div class="sidebar-user">
            <div class="category-content">
              <% if company_signed_in? %>
              <div class="media">
                <a href="#" class="media-left"><img src="/assets/images/placeholder.jpg" class="img-circle img-sm" alt=""></a>
                <div class="media-body">
                  <span class="media-heading text-semibold"><%= current_company.name %></span>
                  <div class="text-size-mini text-muted">
                    <i class="icon-pin text-size-small"></i> <%= current_company.prefecture %>
                  </div>
                </div>

                <div class="media-right media-middle">
                  <ul class="icons-list">
                    <li>
                      <a href="#" data-toggle="modal" data-target="#modal_form_horizontal"><i class="icon-cog3"></i></a>
                    </li>
                  </ul>
                </div>
              </div>
              <% end %>
            </div>
          </div>
          <!-- /`nu -->


          <!-- Main navigation -->
          <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
              <ul class="navigation navigation-main navigation-accordion">

                <li>
                  <%= link_to root_path do %>
                  <i class="icon-newspaper"></i> ダッシュボード
                  <% end %>
                </li>

                <!-- projects -->
                <li href="#" class="navigation-header"><span>案件</span> <i class="icon-menu" title="Forms"></i></li>
                <li>
                  <a href="#"><i class="icon-arrow-left16"></i> <span>受注</span></a>
                  <ul>
                    <li><%= link_to '依頼された案件', receive_projects_path %></li>
                    <li><%= link_to '契約を確認', commitments_path %></li>
                  </ul>
                </li>
                <li>
                  <a href="#"><i class=" icon-arrow-right16"></i> <span>発注</span></a>
                  <ul>
                    <li><%= link_to '依頼した案件', order_projects_path %></li>
                    <li><%= link_to '案件を作成', new_project_path %></li>
                    <li><%= link_to '契約を確認', commitments_path %></li>
                  </ul>
                </li>
                <li>
                  <%= link_to companies_path do %>
                  <i class="icon-store"></i> 企業一覧
                  <% end %>
                </li>
                <!-- /projects -->

                <!-- accounts -->
                <li class="navigation-header"><span>アカウント</span> <i class="icon-menu" title="Main pages"></i></li>
                <li>
                  <a href="#" data-toggle="modal" data-target="#modal_form_horizontal"><i class="icon-user-tie"></i> <span>アカウント編集</span></a>
                </li>
                <!-- /accounts -->

              </ul>
            </div>
          </div>
          <!-- /main navigation -->

          <!-- Horizontal form modal -->
          <div id="modal_form_horizontal" class="modal fade">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h5 class="modal-title">アカウント編集</h5>
                </div>

                <form action="#" class="form-horizontal">
                  <div class="modal-body">
                    <div class="panel-body">
                      <div class="form-group">
                        <label>登録Eメール：</label>
                        <input type="text" class="form-control" value="imatat@tatami.jp">
                      </div>

                      <div class="form-group">
                        <label>企業名：</label>
                        <input type="text" class="form-control" value="(株)イマタット畳店">
                      </div>

                      <div class="form-group">
                        <label>郵便番号：</label>
                        <input type="text" class="form-control" value="123-1234">
                      </div>

                      <div class="form-group">
                        <label>住所：</label>
                        <input type="text" class="form-control" value="東京都日野市南平1-1">
                      </div>

                      <div class="form-group">
                        <label class="display-block">都道府県:</label>
                        <select data-placeholder="東京" class="select-fixed" value="東京都">
                          <option></option>
                            <option value="AK">北海道</option>
                            <option value="HI">青森</option>
                            <option value="CA">秋田</option>
                            <option value="NV">岩手</option>
                            <option value="WA">東京</option>
                            <option value="AZ">千葉</option>
                          </optgroup>
                        </select>
                      </div>

                      <div class="form-group">
                        <label>日産(枚)：</label>
                        <input type="text" class="form-control" value="6">
                      </div>

                      <div class="form-group">
                        <label>従業員数(人)：</label>
                        <input type="text" class="form-control" value="2">
                      </div>

                      <div class="form-group">
                        <label>電話番号：</label>
                        <input type="text" class="form-control" value="012-345-6789">
                      </div>

                      <div class="form-group">
                        <label>パスワード：</label>
                        <input type="password" class="form-control" value="">
                      </div>

                      <div class="form-group">
                        <label>パスワード再入力：</label>
                        <input type="password" class="form-control" value="">
                      </div>

                      <div class="form-group">
                        <label>プロフィール画像：</label>
                        <input type="file" class="file-styled">
                      </div>

                      <div class="form-group">
                        <label>企業紹介:</label>
                        <textarea rows="5" cols="5" class="form-control" value="企業紹介"></textarea>
                      </div>

                      <div class="form-group">
                        <label class="display-block">忙しさ:</label>
                        <select data-placeholder="忙しい" class="select-fixed" value="忙しい">
                          <option></option>
                            <option value="highest">とても忙しい</option>
                            <option value="high">忙しい</option>
                            <option value="normal">普通</option>
                            <option value="low">あまり忙しくない</option>
                            <option value="lowest">忙しくない</option>
                          </optgroup>
                        </select>
                      </div>

                      <div class="checkbox checkbox-switchery">
                        <label>
                          <input type="checkbox" class="switchery">
                          非公開設定
                          <span class="help-block">onにすると企業一覧に表示されなくなります</span>
                        </label>
                      </div>
                    </div>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit form</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <!-- /horizontal form modal -->

        </div>
      </div>
      <!-- /main sidebar -->