config/routes.rb
Rails.application.routes.draw do

  devise_for :companies, controllers: {
    registrations:  "companies/registrations",
    sessions:       "companies/sessions",
    passwords:      "companies/passwords"
  }

  root to: "dashboard#index"

  match '/account/login', to: 'account#login', via: 'get'
  match '/account/registration', registrationto: 'account#', via: 'get'

  resources :projects do
    resources :comments, except: [:index, :show, :delete]
  end
  match 'order_projects', to: 'projects#order_index', via: 'get'
  match 'receive_projects', to: 'projects#receive_index', via: 'get'

  resources :commitments, except: [:show]

  resources :reviews, only: [:new, :create]

  resources :companies
end

app/models/project.rb
class Project < ActiveRecord::Base

  extend Enumerize
  enumerize :status, in: [:public, :private, :closed]


  has_many :comments
  has_many :commitments

  belongs_to :company # source_company

  def source_company_name; Company.where(id: source_company_id).first.name; end
  def dest_company_name; Company.where(id: dest_company_id).first.name; end

  # validates :source_company_id,          presence: true
  # validates :dest_company_id,          presence: true
  # validates :status,              presence: true
  # validates :name,                presence: true
  # validates :body,                presence: true
  # validates :kind_body,           presence: true
  # validates :kind_edge,           presence: true
  # validates :need_amount,         presence: true
  # validates :deadline,            presence: true
  # validates :estimated_sum,       presence: true
  # validates :note,                presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  protect_from_forgery except: :update

  def index
  end

  def new
    @project = Project.new

    if company_signed_in?
      @dest_companies = Company.where(status: 'public').reject(id: current_company.id)
    else
      @dest_companies = Company.where(status: 'public')
    end
  end

  def create
    @project = Project.new(project_params)
    if company_signed_in?
      @project.source_company_id = current_company.id
    else
      @project.source_company_id = Company.first.id
    end
    if @project.save
      flash[:success] = "making project is success!"
      redirect_to @project
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
    @comment = @project.comments.build
    @source_company = Company.where(id: @project.source_company_id).first

    neg_companies = []
    Comment.where(project_id: params[:id]).all.each do |comment|
      neg_companies << Company.where(id: comment.company_id).first
    end
    @neg_companies = neg_companies.uniq

  end

  def order_index
    if company_signed_in?
      one = Project.where(source_company_id: current_company.id).order(:id)
    else
      one = Project.all.order(:id)
    end

    if one.search(params[:q])
      @q        = one.search(params[:q])
      @projects = @q.result(distinct: true)
    else
      @projects = one.where(status: 'public').all
    end
  end

  def receive_index
    if company_signed_in?
      one = Project.where(dest_company_id: current_company.id || nil).order(:id)
    else
      one = Project.all.order(:id)
    end

    if one.search(params[:q])
      @q        = one.search(params[:q])
      @projects = @q.result(distinct: true)
    else
      @projects = one.where(status: 'public').all
    end
  end

  def edit
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:success] = "Project updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project deleted"
    redirect_to order_projects_path
  end

  private

  def project_params
    params.require(:project).permit(
      :source_company_id,
      :dest_company_id,
      :status,
      :name,
      :body,
      :kind_body,
      :kind_edge,
      :need_amount,
      :deadline,
      :estimated_sum,
      :note
    )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def calc_post_time_str(created_time)
    time_ago_str = ''
    if (Time.now - created_time).to_i/3600 < 1
      time_ago_str = ((Time.now - created_time).to_i/60).to_s + " minutes"
    else
    time_ago_str = ((Time.now - created_time).to_i/3600).to_s + " hour"
    end
    time_ago_str
  end

  def project_progress_bar(pro)
    amount = 0
    pro.commitments.each do |commitment|
      commitment.amount += amount
    end
    progress = amount / pro.need_amount * 100
    progress.round
  end

  def project_company_status(pro)
    if company_signed_in?
      if pro.comments.where(company_id: current_company.id).present?
        return '交渉中'
      elsif Commitment.where(project_id: pro.id, dest_company_id: current_company.id).present?
        return '契約済み'
      else
        return '未参加'
      end
    else
      if pro.comments.where(company_id: Company.first.id).present?
        return '交渉中'
      elsif Commitment.where(project_id: pro.id, dest_company_id: Company.first.id).present?
        return '契約済み'
      else
        return '未参加'
      end
    end
  end
end

app/views/projects/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>案件作成 | imaTat</title>

  <%= render 'shared/global_style' %>
  <%= render 'shared/core_js' %>

  <!-- Theme JS files -->
  <script type="text/javascript" src="/assets/js/plugins/forms/selects/select2.min.js"></script>
  <script type="text/javascript" src="/assets/js/plugins/forms/styling/uniform.min.js"></script>

  <script type="text/javascript" src="/assets/js/core/app.js"></script>
  <script type="text/javascript" src="/assets/js/pages/form_layouts.js"></script>

  <!-- /theme JS files -->
</head>

<body>

  <%= render 'shared/header_aft' %>

  <!-- Page container -->
  <div class="page-container">

    <!-- Page content -->
    <div class="page-content">

      <%= render 'shared/sidebar' %>

      <!-- Main content -->
      <div class="content-wrapper">

        <!-- Inside page title -->
        <div class="panel border-top-primary">
        </div>
        <div class="panel border-top-primary">
        </div>

        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>

        <div class="page-header">
          <div class="page-header-content">
            <div class="page-title">
              <h5>
                <i class="icon-pencil6 position-left"></i> <span class="text-semibold">imaTat</span> - 案件作成
                <small class="display-block">新しい案件を作成しましょう。</small>
              </h5>
            </div>

            <div class="heading-elements">
              <ul class="breadcrumb">
                <li><a href="index.html"><i class="icon-newspaper position-left"></i> ダッシュボード</a></li>
                <li><i class="icon-pencil6 position-left"></i> 案件作成</li>
              </ul>
            </div>
          </div>
        </div>
        <!-- /inside page title -->


        <!-- Content area -->
        <div class="content">

          <!-- 2 columns form -->
          <%= form_for @project, html: { :class => 'new_project_form'} do |f| %>

            <div class="panel panel-flat">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-6">
                    <fieldset>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">依頼元企業:</label>
                        <div class="col-lg-9">
                          <% if company_signed_in? %>
                            <input type="text" class="form-control" placeholder="<%= current_company.name %>" disabled="true">
                            <% f.text_field :source_company_id, class: 'form-control', value: "#{@current_company.id}" %>
                          <% else %>
                            <input type="text" class="form-control" placeholder="<%= Company.first.name %>" disabled="true"></input>
                            <% f.text_field :source_company_id, class: 'form-control', value: "#{Company.first.id}" %>
                          <% end %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">依頼先企業:</label>
                        <%= f.select :dest_company_id, @dest_companies.all.map { |c| [c.name, c.id] }, { include_blank: true }, { class: 'searchable' } %>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">ステータス:</label>
                        <%= f.select :status, {'公開' => 'public', '非公開' => 'private'}, class: 'select' %>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">案件名:</label>
                        <div class="col-lg-9">
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">案件詳細:</label>
                        <div class="col-lg-9">
                          <%= f.text_area :body, rows: '10', cols: '5', class: 'form-control' %>
                        </div>
                      </div>
                    </fieldset>
                  </div>

                  <div class="col-md-6">
                    <fieldset>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">畳表:</label>
                        <div class="col-lg-9">
                          <%= f.text_field :kind_body, class: 'form-control' %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">畳縁:</label>
                        <div class="col-lg-9">
                          <%= f.text_field :kind_edge, class: 'form-control' %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">必要数量(畳):</label>
                        <div class="col-lg-9">
                          <%= f.text_field :need_amount, class: 'form-control' %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">見積額(円/1畳):</label>
                        <div class="col-lg-9">
                          <%= f.text_field :estimated_sum, class: 'form-control' %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">納期:</label>
                        <div class="col-lg-9">
                          <%= f.text_field :deadline, class: 'form-control daterange-single', value: "#{Date.today}" %>
                        </div>
                      </div>
                      <br><br>
                      <div class="form-group">
                        <label class="col-lg-3 control-label">備考:</label>
                        <div class="col-lg-9">
                          <%= f.text_area :note, rows: '10', cols: '5', class: 'form-control' %>
                        </div>
                      </div>
                    </fieldset>
                  </div>
                </div>

                <div class="text-right">
                  <button type="submit" class="btn btn-primary">作成 <i class="icon-arrow-right14 position-right"></i></button>
                </div>
              </div>
            </div>

          <% end %>
          <!-- /2 columns form -->


          <%= render 'shared/footer' %>

        </div>
        <!-- /content area -->

      </div>
      <!-- /main content -->

    </div>
    <!-- /page content -->

  </div>
  <!-- /page container -->

</body>
</html>

app/views/projects/order_index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>依頼した案件 | imaTat</title>

  <%= render 'shared/global_style' %>
  <%= render 'shared/core_js' %>

	<!-- Theme JS files -->
	<script type="text/javascript" src="assets/js/core/app.js"></script>
	<!-- /theme JS files -->

</head>

<body>

  <%= render 'shared/header_aft' %>

	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

      <%= render 'shared/sidebar' %>

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Inside page title -->
				<div class="panel border-top-primary">
				</div>
				<div class="panel border-top-primary">
				</div>

        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>

				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h5>
								<i class="icon-arrow-right16 position-left"></i> <span class="text-semibold">imaTat</span> - 依頼した案件
								<small class="display-block">あなたが作成した案件です。コメントを確認して契約をしましょう！</small>
							</h5>
						</div>

						<div class="heading-elements">
							<ul class="breadcrumb">
								<li><a href="index.html"><i class="icon-newspaper position-left"></i> ダッシュボード</a></li>
								<li><i class="icon-arrow-right16 position-left"></i> 依頼した案件</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /inside page title -->


				<!-- Content area -->
				<div class="content">

					<!-- Search field -->
					<div class="panel panel-flat">
						<div class="panel-heading">
							<h5 class="panel-title">検索</h5>
							<div class="heading-elements">
								<ul class="icons-list">
									<li><a data-action="collapse"></a></li>
								</ul>
							</div>
						</div>

						<div class="panel-body">
							<%= search_form_for @q do |f| %>
							<form action="#" class="main-search">
								<div class="input-group content-group">
									<div class="has-feedback has-feedback-left">
										<%= f.search_field :name_cont, class: 'form-control input-xlg', placeholder: '案件名で検索できます'%>
										<div class="form-control-feedback">
											<i class="icon-search4 text-muted text-size-base"></i>
										</div>
									</div>

									<div class="input-group-btn">
										<button type="submit" class="btn btn-primary btn-xlg">検索</button>
									</div>
								</div>
							</form>
							<% end %>
						</div>
					</div>
					<!-- /search field -->

					<!-- Search results -->
					<div class="content-group">
						<p class="text-muted text-size-small content-group">About <%= @projects.count %> results</p>

						<div class="search-results-list content-group">
  						<div class="panel panel-flat">
  							<div class="panel-heading">
  								<h5 class="panel-title">検索結果</h5>
  								<div class="heading-elements">
  									<ul class="icons-list">
  										<li><a data-action="reload"></a></li>
  									</ul>
  								</div>
  							</div>

  							<div class="table-responsive">
  								<table class="table">
  									<thead>
  										<tr class="bg-info">
  											<th style="width: 130px;">ステータス</th>
  											<th>案件名</th>
  											<th style="width: 140px;">依頼先</th>
  											<th style="width: 90px;">納期</th>
  											<th style="width: 250px;">契約進捗</th>
  											<th style="width: 140px;"></th>
  									</thead>
  									<tbody>
                      <% @projects.each do |project| %>
  										<tr>
  											<td><%= project.status %></td>
  											<td><%= project.name %></td>
                        <% if project.dest_company_id == nil %>
                          <td>一般公開</td>
                        <% elsif project.dest_company_id %>
                          <td><%= link_to "#{project.dest_company_name}", company_path(Company.where(id: project.dest_company_id).first) %></td>
                        <% end %>
  											<td><%= project.deadline %></td>
  											<td>
  												<div class="progress">
  													<div class="progress-bar bg-info" style="width: <%= project_progress_bar(project) %>%">
  														<span><%= project_progress_bar(project) %></span>
  													</div>
  												</div>
  												</div>
  											</td>
  											<td>
  												<%= link_to '詳細', project_path(project), {class: 'btn btn-info btn-xs'} %>
                          <%= link_to('削除', project, method: :delete, class: "btn btn-info btn-xs") %>
  											</td>
  										</tr>
                      <% end %>
  									</tbody>
  								</table>
  							</div>
  						</div>
						</div>
					</div>
					<!-- /search results -->

          <%= render 'shared/footer' %>

				</div>
				<!-- /content area -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->

</body>
</html>

app/views/projects/receive_index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>依頼された案件 | imaTat</title>

  <%= render 'shared/global_style' %>
  <%= render 'shared/core_js' %>

	<!-- Theme JS files -->
	<script type="text/javascript" src="assets/js/core/app.js"></script>
	<!-- /theme JS files -->

</head>

<body>

  <%= render 'shared/header_aft' %>

	<!-- Page container -->
	<div class="page-container">

		<!-- Page content -->
		<div class="page-content">

      <%= render 'shared/sidebar' %>

			<!-- Main content -->
			<div class="content-wrapper">

				<!-- Inside page title -->
				<div class="panel border-top-primary">
				</div>
				<div class="panel border-top-primary">
				</div>

        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>

				<div class="page-header">
					<div class="page-header-content">
						<div class="page-title">
							<h5>
								<i class="icon-arrow-left16 position-left"></i> <span class="text-semibold">imaTat</span> - 依頼された案件
								<small class="display-block">あなたが依頼された案件です。詳細ページから受注申請してみましょう。</small>
							</h5>
						</div>

						<div class="heading-elements">
							<ul class="breadcrumb">
								<li><a href="index.html"><i class="icon-newspaper position-left"></i> ダッシュボード</a></li>
								<li><i class="icon-arrow-left16 position-left"></i> 依頼された案件</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /inside page title -->


				<!-- Content area -->
				<div class="content">

					<!-- Search field -->
					<div class="panel panel-flat">
						<div class="panel-heading">
							<h5 class="panel-title">検索</h5>
							<div class="heading-elements">
								<ul class="icons-list">
									<li><a data-action="collapse"></a></li>
								</ul>
							</div>
						</div>

						<div class="panel-body">
							<form action="#" class="main-search">
								<div class="input-group content-group">
									<div class="has-feedback has-feedback-left">
										<input type="text" class="form-control input-xlg" placeholder="案件名、企業名で検索できます">
										<div class="form-control-feedback">
											<i class="icon-search4 text-muted text-size-base"></i>
										</div>
									</div>

									<div class="input-group-btn">
										<button type="submit" class="btn btn-primary btn-xlg">検索</button>
									</div>
								</div>

								<div class="row search-option-buttons">

								</div>
							</form>
						</div>
					</div>
					<!-- /search field -->

					<!-- Search results -->
					<div class="content-group">
            <p class="text-muted text-size-small content-group">About <%= @projects.count %> results</p>

						<div class="search-results-list content-group">

						<div class="panel panel-flat">
							<div class="panel-heading">
								<h5 class="panel-title">検索結果</h5>
								<div class="heading-elements">
									<ul class="icons-list">
										<li><a data-action="reload"></a></li>
									</ul>
								</div>
							</div>

							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr class="bg-info">
                      <th style="width: 130px;">ステータス</th>
                      <th>案件名</th>
                      <th style="width: 140px;">依頼元</th>
                      <th style="width: 90px;">納期</th>
                      <th style="width: 250px;">契約進捗</th>
                      <th style="width: 140px;"></th>
									</thead>
									<tbody>
                    <% @projects.each do |project| %>
										<tr>
											<td><%= project_company_status(project) %></td>
                      <td><%= project.name %></td>
                      <td><%= link_to "#{project.source_company_name}", company_path(Company.where(id: project.source_company_id).first) %></td>
                      <td><%= project.deadline %></td>
											<td>
												<div class="progress">
													<div class="progress-bar bg-info" style="width: <%= project_progress_bar(project) %>%">
														<span><%= project_progress_bar(project) %></span>
													</div>
												</div>
												</div>
											</td>
											<td>
                        <%= link_to '詳細', project_path(project), {class: 'btn btn-info btn-xs'} %>
                        <%= link_to '契約', commitments_path, {class: 'btn btn-info btn-xs'} %>
											</td>
										</tr>
                    <% end %>
									</tbody>
								</table>
							</div>
						</div>

						</div>
					</div>
					<!-- /search results -->

		      <!-- Vertical form modal -->
					<div id="modal_form_vertical" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h5 class="modal-title">詳細検索</h5>
								</div>

								<form action="#">
									<div class="modal-footer">
										<button type="button" class="btn btn-link" data-dismiss="modal">閉じる</button>
										<button type="submit" class="btn btn-primary">検索</button>
									</div>
								</form>
							</div>
						</div>
					</div>
					<!-- /vertical form modal -->

          <%= render 'shared/footer' %>

				</div>
				<!-- /content area -->

			</div>
			<!-- /main content -->

		</div>
		<!-- /page content -->

	</div>
	<!-- /page container -->

</body>
</html>